# TCL File Generated by Component Editor 13.0sp1
# Tue Mar 04 19:28:50 BRT 2025
# DO NOT MODIFY


# 
# aes_dec "aes_dec" v1.0
#  2025.03.04.19:28:50
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module aes_dec
# 
set_module_property DESCRIPTION ""
set_module_property NAME aes_dec
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME aes_dec
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL AES_decypher_avalon
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file Reg.vhd VHDL PATH hw_dec/Reg.vhd
add_fileset_file Sbox.vhd VHDL PATH hw_dec/Sbox.vhd
add_fileset_file inv_Sbox.vhd VHDL PATH hw_dec/inv_Sbox.vhd
add_fileset_file Gf_mult_2.vhd VHDL PATH hw_dec/Gf_mult_2.vhd
add_fileset_file inv_Sub_bytes.vhd VHDL PATH hw_dec/inv_Sub_bytes.vhd
add_fileset_file inv_Shift_rows.vhd VHDL PATH hw_dec/inv_Shift_rows.vhd
add_fileset_file Column_operator.vhd VHDL PATH hw_dec/Column_operator.vhd
add_fileset_file inv_Column_operator.vhd VHDL PATH hw_dec/inv_Column_operator.vhd
add_fileset_file inv_Mix_columns.vhd VHDL PATH hw_dec/inv_Mix_columns.vhd
add_fileset_file Round_key_adder.vhd VHDL PATH hw_dec/Round_key_adder.vhd
add_fileset_file inv_Round_key_calculator.vhd VHDL PATH hw_dec/inv_Round_key_calculator.vhd
add_fileset_file Key_scheduler.vhd VHDL PATH hw_dec/Key_scheduler.vhd
add_fileset_file Controller.vhd VHDL PATH hw_dec/Controller.vhd
add_fileset_file AES_decypher.vhd VHDL PATH hw_dec/AES_decypher.vhd
add_fileset_file AES_decypher_avalon.vhd VHDL PATH hw_dec/AES_decypher_avalon.vhd TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock CLK clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 READDATA readdata Output 32
add_interface_port avalon_slave_0 WRITEDATA writedata Input 32
add_interface_port avalon_slave_0 ADD address Input 6
add_interface_port avalon_slave_0 CS chipselect Input 1
add_interface_port avalon_slave_0 WR_EN write Input 1
add_interface_port avalon_slave_0 RD_EN read Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink RST_N reset_n Input 1

