# TCL File Generated by Component Editor 13.0sp1
# Wed Feb 26 15:41:28 BRT 2025
# DO NOT MODIFY


# 
# dec "dec" v1.0
#  2025.02.26.15:41:28
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module dec
# 
set_module_property DESCRIPTION ""
set_module_property NAME dec
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME dec
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL decryptor
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file add_round_key.vhd VHDL PATH hw/add_round_key.vhd
add_fileset_file aes_dec.vhd VHDL PATH hw/aes_dec.vhd
add_fileset_file column_calculator.vhd VHDL PATH hw/column_calculator.vhd
add_fileset_file controller.vhd VHDL PATH hw/controller.vhd
add_fileset_file dec.vhd VHDL PATH hw/dec.vhd TOP_LEVEL_FILE
add_fileset_file gfmult_by2.vhd VHDL PATH hw/gfmult_by2.vhd
add_fileset_file inv_column_calculator.vhd VHDL PATH hw/inv_column_calculator.vhd
add_fileset_file inv_key_sch_round_function.vhd VHDL PATH hw/inv_key_sch_round_function.vhd
add_fileset_file inv_mix_columns.vhd VHDL PATH hw/inv_mix_columns.vhd
add_fileset_file inv_sbox.vhd VHDL PATH hw/inv_sbox.vhd
add_fileset_file inv_shift_rwos.vhd VHDL PATH hw/inv_shift_rwos.vhd
add_fileset_file inv_sub_byte.vhd VHDL PATH hw/inv_sub_byte.vhd
add_fileset_file key_schedule.vhd VHDL PATH hw/key_schedule.vhd
add_fileset_file mix_columns.vhd VHDL PATH hw/mix_columns.vhd
add_fileset_file reg.vhd VHDL PATH hw/reg.vhd
add_fileset_file sbox.vhd VHDL PATH hw/sbox.vhd


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 wr_enable write Input 1
add_interface_port avalon_slave_0 chip_select chipselect Input 1
add_interface_port avalon_slave_0 data_in writedata Input 32
add_interface_port avalon_slave_0 data_out readdata Output 32
add_interface_port avalon_slave_0 read_enable read Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

